//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrm.Model.Constants
{
    
    /// <summary>
    /// Веб-ресурс (webresource)
    /// Данные, эквивалентные файлам, используемым в разработке веб-контента. Веб-ресурсы обеспечивают компоненты на стороне клиента, которые используются для создания настраиваемых элементов интерфейса пользователя.
    /// </summary>
    public sealed class WebResource
    {
        /// <summary>
        /// LogicalName (webresource)
        /// </summary>
        public const string LogicalName = "webresource";
        /// <summary>
        /// Id (webresourceid)
        /// </summary>
        public const string Id = "webresourceid";
        /// <summary>
        /// PrimaryAttribute (name)
        /// </summary>
        public const string PrimaryAttribute = "name";
        /// <summary>
        /// Owner (ownerid)
        /// </summary>
        public const string Owner = "ownerid";
        /// <summary>
        /// State (statecode)
        /// </summary>
        public const string State = "statecode";
        /// <summary>
        /// Status (statuscode)
        /// </summary>
        public const string Status = "statuscode";
        /// <summary>
        /// Состояние компонента (componentstate)
        /// Только для внутреннего использования.
        /// </summary>
        public const string componentstate = "componentstate";
        /// <summary>
        ///  (content)
        /// Размер веб-ресурса в байтах в формате Base64.
        /// </summary>
        public const string content = "content";
        /// <summary>
        ///  (contentjson)
        /// JSON-представление содержимого ресурса.
        /// </summary>
        public const string contentjson = "contentjson";
        /// <summary>
        /// Создано (createdby)
        /// Уникальный идентификатор пользователя, создавшего веб-ресурс.
        /// </summary>
        public const string createdby = "createdby";
        /// <summary>
        /// Дата создания (createdon)
        /// Дата и время создания веб-ресурса.
        /// </summary>
        public const string createdon = "createdon";
        /// <summary>
        /// Кем создано (делегат) (createdonbehalfby)
        /// Уникальный идентификатор делегата, создавшего веб-ресурс.
        /// </summary>
        public const string createdonbehalfby = "createdonbehalfby";
        /// <summary>
        /// DependencyXML (dependencyxml)
        /// Только для внутреннего использования.
        /// </summary>
        public const string dependencyxml = "dependencyxml";
        /// <summary>
        /// Описание (description)
        /// Описание веб-ресурса.
        /// </summary>
        public const string description = "description";
        /// <summary>
        /// Отображаемое имя (displayname)
        /// Отображаемое имя веб-ресурса.
        /// </summary>
        public const string displayname = "displayname";
        /// <summary>
        /// Версия введения (introducedversion)
        /// Версия, в которой была введена форма.
        /// </summary>
        public const string introducedversion = "introducedversion";
        /// <summary>
        /// Доступен для Mobile Offline (isavailableformobileoffline)
        /// Сведения, которые определяют, доступен ли этот веб-ресурс для мобильного клиента в автономном режиме.
        /// </summary>
        public const string isavailableformobileoffline = "isavailableformobileoffline";
        /// <summary>
        /// Включен для мобильного клиента (isenabledformobileclient)
        /// Сведения, которые определяют, включен ли этот веб-ресурс для мобильного клиента.
        /// </summary>
        public const string isenabledformobileclient = "isenabledformobileclient";
        /// <summary>
        ///  (ismanaged)
        /// </summary>
        public const string ismanaged = "ismanaged";
        /// <summary>
        /// Язык (languagecode)
        /// Язык веб-ресурса.
        /// </summary>
        public const string languagecode = "languagecode";
        /// <summary>
        /// Изменено (modifiedby)
        /// Уникальный идентификатор пользователя, внесшего последнее изменение в веб-ресурс.
        /// </summary>
        public const string modifiedby = "modifiedby";
        /// <summary>
        /// Дата изменения (modifiedon)
        /// Дата и время внесения последнего изменения в веб-ресурс.
        /// </summary>
        public const string modifiedon = "modifiedon";
        /// <summary>
        /// Кем создано (делегат) (modifiedonbehalfby)
        /// Уникальный идентификатор делегата, внесшего последнее изменение в веб-ресурс.
        /// </summary>
        public const string modifiedonbehalfby = "modifiedonbehalfby";
        /// <summary>
        /// Имя (name)
        /// Название веб-ресурса.
        /// </summary>
        public const string name = "name";
        /// <summary>
        /// Предприятие (organizationid)
        /// Уникальный идентификатор организации, связанной с веб-ресурсом.
        /// </summary>
        public const string organizationid = "organizationid";
        /// <summary>
        /// Время замены записи (overwritetime)
        /// Только для внутреннего использования.
        /// </summary>
        public const string overwritetime = "overwritetime";
        /// <summary>
        /// Версия Silverlight (silverlightversion)
        /// Номер версии среды выполнения Silverlight, которая требуется веб-ресурсу Silverlight.
        /// </summary>
        public const string silverlightversion = "silverlightversion";
        /// <summary>
        /// Решение (solutionid)
        /// Уникальный идентификатор связанного решения.
        /// </summary>
        public const string solutionid = "solutionid";
        /// <summary>
        /// Решение (supportingsolutionid)
        /// Только для внутреннего использования.
        /// </summary>
        public const string supportingsolutionid = "supportingsolutionid";
        /// <summary>
        /// Идентификатор веб-ресурса (webresourceid)
        /// Уникальный идентификатор веб-ресурса.
        /// </summary>
        public const string webresourceid = "webresourceid";
        /// <summary>
        ///  (webresourceidunique)
        /// Только для внутреннего использования.
        /// </summary>
        public const string webresourceidunique = "webresourceidunique";
        /// <summary>
        /// Тип (webresourcetype)
        /// Раскрывающийся список для выбора типа веб-ресурса.
        /// </summary>
        public const string webresourcetype = "webresourcetype";
    }
}
