# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the working branch
  push:
    branches: [ working ]
  pull_request:
    branches: [ working ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout sources
        uses: actions/checkout@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
        
      - name: Navigate to sources
        run: cd ${env:GITHUB_WORKSPACE}

      - name: Restore packages
        run: nuget restore Wrm.sln
        
      - name: Build
        run: msbuild.exe Wrm.sln /p:outdir="output" /p:platform="any cpu" /p:configuration="release" /nr:false /nologo      
  
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wrm-cs
          path: Wrm.Console/output/*
